### ISSUE TITLE
Pull Request yapmayi kolaylastirmaliyiz

### ISSUE THREAD

**Issue by f9n** [GnuYtuce/Ytuce-Lectures#3]
Insanlar reponun boyutu cok buyuk oldugu icin indirmezler.
Pull Request yerine Email Bot veya Telegram Bot yapabiliriz.
Insanlar Belli bir standart icin de Bot'a dosya gonderir.
Botta repo'ya push'lar, commit iceriginde de kullanicinin mail adresi veya ismi yazilir('Eyvallah Burak' veya 'Eyvallah cilgin_burak@gmail.com').
Ayrica Readme.md'e eklenir.

**Comment by Emre-Kul** [comment]
Her ders için ayrı branch açılabilir böylece sadece o dersin kaynaklarına ihtiyacı olan biri branch'ı clonlar,
bu Pull Request sorununa da çözüm olabilir.Son olarak master'da readme dosyasından bu alt brachlar için link verilebilir.

**Comment by hibestil** [comment]
Güzel fikir :tada:
