### ISSUE TITLE
İsim hatası

### ISSUE THREAD

**Issue by yunustiras** [GnuYtuce/Ytuce-Lectures#7]
https://github.com/GnuYtuce/Ytuce-Lectures/tree/BLM2502/BLM2502-ComputingTheory(HesaplamaKurami)/2015-2016/FerkanYilmaz/Slayts dizininin adı 
https://github.com/GnuYtuce/Ytuce-Lectures/tree/BLM2502/BLM2502-ComputingTheory(HesaplamaKurami)/2015-2016/FerkanYilmaz/Slides olarak düzeltilmeli.

**Comment by f9n** [comment]
Teşekkürler :+1: 

https://github.com/GnuYtuce/Ytuce-Lectures/commits/43dd89861576ca24bbd853dfd6d931dbc54ecbf4
